apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  amdp.io/app: amdp-studio-manager
  amdp.io/profile: hj-pjt-1.dev
configMapGenerator:
- behavior: merge
  files:
  - application-custom.yaml
  name: app-config
images:
- !!skcc.generate.model.kustomize.ImagePatchModel
  name: app
  newName: amdp-registry.skamdp.org/am-studio/manager
  newTag: latest
kind: Kustomization
namePrefix: amdp-studio-manager-
nameSuffix: -dev
patchesJson6902:
- path: service-patch.yaml
  target:
    kind: Service
    name: app
    version: v1
patchesStrategicMerge:
- container-patch.yaml
- imagepolicy-patch.yaml
- pod-lifecycle-patch.yaml
- probe-patch.yaml
- spec-patch.yaml
- replicas-patch.yaml
- nodegroup-patch.yaml
- toleration-patch.yaml
- active-profiles-patch.yaml
- pod-template-annotation-patch.yaml
- istio-injection-patch.yaml
resources:
- ../common/deployment
