apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/deployment-spa-type1
  - ../resource/role.yaml # SA for dev environment
  - ../resource/sa.yaml
patches:
  - path: ../resource/configmap-reader-patch.yaml
    target:
      group: apps
      version: v1
      name: app
