!!skcc.generate.model.hash.MicroserviceTemplateHashPatchModel
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    metadata:
      annotations:
        amdp.io/hash: XVfbMDNMjg
