apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 128Mi
