apiVersion: batch/v1
kind: Job
metadata:
  name: app
spec:
  backoffLimit: 6
  completions: 1
  suspend: false
  template:
    spec:
      restartPolicy: Always
    labels:
      job-version: "2022-05-26 17:46:43" # current time