apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../common/deployment
namePrefix: <%=name%>-
nameSuffix: -<%=name_suffix%>
commonLabels:
  project: <%=project_name%>
  microservice: <%=name%>
configMapGenerator:
  - name: app-config
    behavior: merge
    files:
      - application-custom.yaml
images:
  - name: app
    newName: <%=imageregistry_url%>/<%=image_project%>/<%=image_name%>
    newTag: <%=image_tag%>
patchesStrategicMerge:
  - container-patch.yaml
  - imagepolicy-patch.yaml
  - pod-lifecycle-patch.yaml
  - probe-patch.yaml
  - replicas-patch.yaml
  - spec-patch.yaml
patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: app
    path: service-patch.yaml
