apiVersion: <%=api_version%>
kind: <%=deploy_type%>
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: <%=mariadb_name%>-secret
              key: user
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: <%=mariadb_name%>-secret
              key: password