apiVersion: <%=api_version%>
kind: <%=deploy_type%>
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: ORACLE_USER
          valueFrom:
            secretKeyRef:
              name: <%=oracle_name%>-secret
              key: user
        - name: ORACLE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: <%=oracle_name%>-secret
              key: password