apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  amdp.io/app: argocd-spring
  amdp.io/profile: hj-pjt-1.dev
configMapGenerator:
- behavior: merge
  files:
  - application-custom.yaml
  name: app-config
images:
- name: app
  newName: amdp-registry.skamdp.org/hj-pjt-1/dev/argocd-spring
  newTag: latest
kind: Kustomization
namePrefix: argocd-spring-
nameSuffix: -dev
patchesJson6902:
- path: service-patch.yaml
  target:
    kind: Service
    name: app
    version: v1
patchesStrategicMerge:
- container-patch.yaml
- imagepolicy-patch.yaml
- pod-lifecycle-patch.yaml
- probe-patch.yaml
- spec-patch.yaml
- replicas-patch.yaml
- active-profiles-patch.yaml
- pod-template-annotation-patch.yaml
- istio-injection-patch.yaml
resources:
- ../common/deployment
