apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - job.yaml
  - cronjob.yaml
  - service.yaml
configMapGenerator:
  - name: app-config
    files:
    - ../common/application.yaml