!!skcc.generate.model.profile.ActiveProfilePatchModel
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: stock,common,custom
        name: app
