apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
spec:
  serviceName: app
  replicas: 1
  template:
    spec:
      containers:
      - name: app
        image: app
        # ports:
        # - containerPort: 8080
        #   name: web
        volumeMounts:
        - mountPath: /config
          name: app-config-volume
      volumes:
      - name: app-config-volume
        configMap:
          name: app-config
